"""ExtraCreditColumns

Revision ID: c884ec1edd99
Revises: 0d70714eefad
Create Date: 2026-06-06 23:18:50.841699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c884ec1edd99'
down_revision: Union[str, Sequence[str], None] = '0d70714eefad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.add_column('feedback', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('feedback', sa.Column('assignee', sa.String(length=100), nullable=True))
    op.add_column('feedback', sa.Column('language', sa.String(length=10), nullable=True))
    op.drop_index(op.f('ix_feedback_category'), table_name='feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedback_category'), 'feedback', ['category'], unique=False)
    op.drop_column('feedback', 'language')
    op.drop_column('feedback', 'assignee')
    op.drop_column('feedback', 'status')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
